markdown: kramdown
title                    : "GitHub Pages 따라하기- devinlfe.github.io"
name                     : "취미코딩하는 개발자"
description              : "회사에서는 월급 받고 집에서는 취미로 코딩하는 개발자의 블로그"
url                      : "https://devinlife.github.io"
baseurl                  : # 서브 경로가 있는 경우 기재